# -*- coding: utf-8 -*-
"""Handling_missing_values.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11ZdJtT19wvb7jWvQ2E3zZPzuPVOtZLZA
"""

import pandas as pd
import numpy as np

# Read in all our data
nfl_data = pd.read_csv("/content/NFL Play by Play 2009-2016 (v3).csv")

# Set seed for reproducibility
np.random.seed(0)

nfl_data.head()

"""**What is a seed value**

A seed value in the context of random number generation is an initial input that determines the sequence of random numbers produced by a pseudorandom number generator (PRNG).

The function np.random.seed() is used in NumPy to set the seed for the random number generator, ensuring reproducibility of random results.

**How many missing values do we have in each column?**
"""

# Get the number of missing data points
missing_values_count = nfl_data.isnull().sum()

# Look at the missing values in the first ten columns
missing_values_count[0:10]

# How many total missing values do we have
total_cells = np.prod(nfl_data.shape)
total_missing = missing_values_count.sum()

# Percent of data that is missing
percent_missing = (total_missing/total_cells) * 100
print(percent_missing)

# remove all rows that contain a missing value
nfl_data.dropna()

# Remove all columns with at least one missing value
columns_with_na_dropped = nfl_data.dropna(axis=1)
columns_with_na_dropped.head()

# Just how much data did we loose?
print("Columns in original dataset: %d \n" % nfl_data.shape[1])
print("Columns with na's dropped: %d" % columns_with_na_dropped.shape[1])

"""**Fill in missing values automatically**"""

# Get a small number of the NFL dataset
subset_nfl_data = nfl_data.loc[:, 'EPA':'Season'].head()
subset_nfl_data

# Replace NA's value with 0
subset_nfl_data.fillna(0)

# Replace all NA values the value that comes directly after it
# And replace all the remaining NA with 0
subset_nfl_data.fillna(method='bfill', axis=0).fillna(0)

