# -*- coding: utf-8 -*-
"""Parsing_Dates.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jTjQ2X7DK1uwBnPnrJfYtR4_-1w_pp-L
"""

import pandas as pd
import numpy as np
import seaborn as sns
import datetime

# Read our data
landslides = pd.read_csv("/content/catalog.csv")

# Set seed for reproducibility
np.random.seed(0)

landslides.head()

# Print the first few row of the date column
print(landslides['date'].head())

# Check the data type of our data coloumn
landslides['date'].dtype

"""Convert our date columns to datetime"""

# Create a new column, date_parsed with the parsed dates
landslides['date_parsed'] = pd.to_datetime(landslides['date'], format="%m/%d/%y")

# Print the first few rows
landslides['date_parsed'].head()

"""Select the date of the month"""

# Get the date of the month from the date_parsed column
day_of_month_landslides = landslides['date_parsed'].dt.day
day_of_month_landslides

"""Plot the day of the month to check the date parsing"""

# Remove na"s
day_of_month_landslides = day_of_month_landslides.dropna()

# Plot the day of the month
sns.distplot(day_of_month_landslides, kde=False, bins=31)

"""******

**EARHTQUAKE DATASET**

************************
"""

earthquakes = pd.read_csv("/content/database.csv")
earthquakes.tail()

earthquakes["Date"].dtype

earthquakes[3378:3383]

date_lengths = earthquakes.Date.str.len()
date_lengths.value_counts()

indices = np.where([date_lengths == 24])[1]
print("Indices with corrupted data:", indices)
earthquakes.loc[indices]

earthquakes.loc[3378, "Date"] = "02/23/1975"
earthquakes.loc[7512, "Date"] = "04/28/1985"
earthquakes.loc[20650, "Date"] = "03/13/2011"
earthquakes['date_parsed'] = pd.to_datetime(earthquakes['Date'], format="%m/%d/%Y")

earhtquakes['date_parsed'] = pd.to_datetime(earthquakes['Date'], format="%m/%d/%Y")

